# Generated by Django 4.2.1 on 2023-05-04 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ciclo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('malla', models.CharField(max_length=50)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('duracion', models.IntegerField()),
                ('codigo_sence', models.CharField(max_length=50)),
                ('asistencia_minima', models.IntegerField()),
                ('calificacion_minima', models.IntegerField()),
                ('modalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('telefono1', models.CharField(max_length=12)),
                ('telefono2', models.CharField(max_length=12)),
                ('correo1', models.CharField(max_length=50)),
                ('correo2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Rol',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiCheck.rol')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiCheck.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Participante_Empresa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiCheck.empresa')),
                ('id_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiCheck.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Participante_Curso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('asistencia', models.IntegerField()),
                ('condicion', models.CharField(max_length=10)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiCheck.curso')),
                ('id_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiCheck.participante')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiCheck.usuario'),
        ),
    ]
